In [9]:
from game_and_players import *

game = MahjongGame(EAST, EAST, [RandomPlayer() for _ in range(4)])

In [10]:
for i in range(70):
    game.step()

In [11]:
copy_gamestate = copy.deepcopy(game.arbiter.state)

In [12]:
copy_gamestate.hands[0] = torch.zeros(42)

In [14]:
game.arbiter.state.hands[0], copy_gamestate.hands[0]

(tensor([0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 1, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        dtype=torch.uint8),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [12]:
torch.nonzero(game.arbiter.state.log[5])


tensor([[13],
        [43]])

In [ ]:
game = 

In [72]:
[is_subsequently_called(game.arbiter.state, logline=i) for i in range(40)]

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True]